SNOW-654839: Additional regression test for save_as_table
Attempting to save a new dataframe created out of a
`SELECT *` result failed in 0.8.0 but was fixed by
SNOW-619431 inadvertently.

This change adds an additional test covering a scenario
where a bulk insert is made from data collected through
a SELECT * query (no columns specified).

This is a test-only change. It makes no changes to
any library or API files.

Testing:

  - Ran all of the test suites via pytest
  - Newly added unit test passes on main
  - Verified manually that the unit test:
    - Passes on tag 0.7.0
    - Fails  on tag 0.8.0
    - Passes on tag 0.9.0

Failure in tag 0.8.0 matches the reported issue:

```
FAILED tests/integ/scala/test_dataframe_suite.py::test_write_from_collected_dataframe - TypeError: argument of type 'NoneType' is not iterable
```