SNOW-1348621 Fixed DataFrame creation from dict of Series objects (#1533)
<!---
Please answer these questions before creating your pull request. Thanks!
--->

1. Which Jira issue is this PR addressing? Make sure that there is an
accompanying issue to your PR.

   <!---
   In this section, please add a Snowflake Jira issue number.
   
Note that if a corresponding GitHub issue exists, you should still
include
   the Snowflake Jira issue number. For example, for GitHub issue
https://github.com/snowflakedb/snowpark-python/issues/1400, you should
   add "SNOW-1335071" here.
    --->

   Fixes SNOW-1348621

2. Fill out the following pre-review checklist:

- [x] I am adding a new automated test(s) to verify correctness of my
new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Bug:
```py
# Performing the following loc operation would fail.
>>> df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)
>>> df2 = df.copy()
>>> df2.loc["a", "three"] = 1.0

# However, when you take a closer look the issue is not with loc set but with the way the DataFrame was being generated. Ignore the numbers inside since these are randomly generated.
>>> df2
        one       two     three               # <-- notice how there are two rows of column names instead of one row
        one       two     three
a -0.238524  0.900504       NaN
b -1.603478 -0.715938  0.786343
c -0.603704 -1.046051  0.371374
d       NaN -0.019357  0.353722
NotImplementedError: loc set for multiindex is not yet implemented

# Expected result:
>>> df2
        one       two     three              # <-- only one row
a  0.357285 -1.225845       NaN
b  0.709229  1.120475  1.551948
c -2.173472  0.682472 -0.738533
d       NaN -1.211516  0.222008
```

This is a bug in concat on axis=1 when all the objects are Series.